In [1]:
import pandas as pd

In [2]:
data  = pd.read_csv(r"C:\\Users\\neel\\OneDrive\\Desktop\\ml_project\\data_set\\train.csv")
data

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,78.0,Male,140.0,289.0,High,Yes,Yes,No,25.086206,Yes,...,No,Low,High,9.024681,Medium,222.0,137.0,14.481422,11.320909,Yes
1,64.0,Male,143.0,203.0,Low,Yes,Yes,Yes,23.791361,Yes,...,No,High,Medium,6.543419,Medium,188.0,111.0,6.485267,15.761419,No
2,18.0,Female,147.0,161.0,Low,Yes,Yes,Yes,37.100070,No,...,No,High,High,4.612469,Low,259.0,123.0,3.383982,14.664906,No
3,24.0,Female,145.0,195.0,Medium,Yes,No,No,23.917206,Yes,...,No,Low,Medium,4.964663,High,175.0,101.0,9.998831,14.296107,No
4,49.0,Male,157.0,291.0,Medium,Yes,No,Yes,22.477665,Yes,...,Yes,Low,Low,7.810732,Medium,261.0,99.0,3.111362,15.257110,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,37.0,Male,168.0,221.0,Medium,No,Yes,No,18.751434,Yes,...,No,Low,High,9.204600,High,385.0,145.0,11.497224,5.402544,No
7996,54.0,Female,156.0,261.0,High,No,No,No,27.909549,Yes,...,Yes,Medium,Medium,8.108505,Medium,343.0,138.0,12.966452,19.244289,No
7997,49.0,Female,144.0,228.0,Medium,No,Yes,No,33.563750,Yes,...,No,Low,High,7.650281,Low,106.0,159.0,13.646456,13.027824,No
7998,22.0,Female,137.0,238.0,Low,Yes,No,No,23.752347,No,...,Yes,Medium,Medium,5.011020,High,214.0,92.0,3.374796,14.446374,No
7999,66.0,Female,135.0,287.0,High,Yes,No,No,35.650116,No,...,No,Low,Medium,4.977200,Medium,124.0,103.0,14.360263,19.381659,No

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   8000 non-null   float64
 1   Gender                8000 non-null   object
 2   Blood Pressure        8000 non-null   float64
 3   Cholesterol Level     8000 non-null   float64
 4   Exercise Habits       8000 non-null   object
 5   Smoking               8000 non-null   object
 6   Family Heart Disease  8000 non-null   object
 7   Diabetes              8000 non-null   object
 8   BMI                   8000 non-null   float64
 9   High Blood Pressure   8000 non-null   object
 10  Low HDL Cholesterol   8000 non-null   object
 11  High LDL Cholesterol  8000 non-null   object
 12  Alcohol Consumption   8000 non-null   object
 13  Stress Level          8000 non-null   object
 14  Sleep Hours           8000 non-null   float64
 15  Sugar Consumption     8000 non-null   object
 16  Triglyceride Level    8000 non-null   float64
 17  Fasting Blood Sugar   8000 non-null   float64
 18  CRP Level             8000 non-null   float64
 19  Homocysteine Level    8000 non-null   float64
 20  Heart Disease Status  8000 non-null   object
dtypes: float64(9), object(12)
memory usage: 1.3+ MB

In [4]:
data.describe()

,Age,Blood Pressure,Cholesterol Level,BMI,Sleep Hours,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,49.137715,149.718867,225.284138,29.048551,6.980410,250.809601,119.945919,7.462968,12.447990
std,18.149622,17.548622,43.548764,6.307190,1.751779,87.290182,23.578477,4.334261,4.330006
min,18.000000,120.000000,150.000000,18.002837,4.000605,100.000000,80.000000,0.003647,5.000236
25%,34.000000,134.000000,187.000000,23.643638,5.444300,175.750000,99.000000,3.657989,8.704263
50%,49.000000,149.859434,225.284138,29.048551,6.994365,250.809601,120.000000,7.466649,12.426568
75%,65.000000,165.000000,263.000000,34.491422,8.503551,326.000000,141.000000,11.221605,16.130968
max,80.000000,180.000000,300.000000,39.995797,9.999952,400.000000,160.000000,14.997087,19.997032

In [5]:
data.isnull().sum()

Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Exercise Habits         0
Smoking                 0
Family Heart Disease    0
Diabetes                0
BMI                     0
High Blood Pressure     0
Low HDL Cholesterol     0
High LDL Cholesterol    0
Alcohol Consumption     0
Stress Level            0
Sleep Hours             0
Sugar Consumption       0
Triglyceride Level      0
Fasting Blood Sugar     0
CRP Level               0
Homocysteine Level      0
Heart Disease Status    0
dtype: int64

In [6]:
data.duplicated().sum()

0

In [7]:
cat_columns = data.columns[data.dtypes=="object"]
data[cat_columns]

,Gender,Exercise Habits,Smoking,Family Heart Disease,Diabetes,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sugar Consumption,Heart Disease Status
0,Male,High,Yes,Yes,No,Yes,Yes,No,Low,High,Medium,Yes
1,Male,Low,Yes,Yes,Yes,Yes,Yes,No,High,Medium,Medium,No
2,Female,Low,Yes,Yes,Yes,No,No,No,High,High,Low,No
3,Female,Medium,Yes,No,No,Yes,No,No,Low,Medium,High,No
4,Male,Medium,Yes,No,Yes,Yes,No,Yes,Low,Low,Medium,No
...,...,...,...,...,...,...,...,...,...,...,...,...
7995,Male,Medium,No,Yes,No,Yes,No,No,Low,High,High,No
7996,Female,High,No,No,No,Yes,Yes,Yes,Medium,Medium,Medium,No
7997,Female,Medium,No,Yes,No,Yes,Yes,No,Low,High,Low,No
7998,Female,Low,Yes,No,No,No,Yes,Yes,Medium,Medium,High,No
7999,Female,High,Yes,No,No,No,No,No,Low,Medium,Medium,No

In [8]:
num_columns = data.columns[data.dtypes!="object"]
data[num_columns]

,Age,Blood Pressure,Cholesterol Level,BMI,Sleep Hours,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
0,78.0,140.0,289.0,25.086206,9.024681,222.0,137.0,14.481422,11.320909
1,64.0,143.0,203.0,23.791361,6.543419,188.0,111.0,6.485267,15.761419
2,18.0,147.0,161.0,37.100070,4.612469,259.0,123.0,3.383982,14.664906
3,24.0,145.0,195.0,23.917206,4.964663,175.0,101.0,9.998831,14.296107
4,49.0,157.0,291.0,22.477665,7.810732,261.0,99.0,3.111362,15.257110
...,...,...,...,...,...,...,...,...,...
7995,37.0,168.0,221.0,18.751434,9.204600,385.0,145.0,11.497224,5.402544
7996,54.0,156.0,261.0,27.909549,8.108505,343.0,138.0,12.966452,19.244289
7997,49.0,144.0,228.0,33.563750,7.650281,106.0,159.0,13.646456,13.027824
7998,22.0,137.0,238.0,23.752347,5.011020,214.0,92.0,3.374796,14.446374
7999,66.0,135.0,287.0,35.650116,4.977200,124.0,103.0,14.360263,19.381659

In [9]:
for col in cat_columns:
    print( data[col].value_counts())
    print(f"Total count {len(data[col].value_counts())}")
    print("================================================")

Gender
Female    4011
Male      3989
Name: count, dtype: int64
Total count 2
================================================
Exercise Habits
High      2716
Medium    2672
Low       2612
Name: count, dtype: int64
Total count 3
================================================
Smoking
Yes    4088
No     3912
Name: count, dtype: int64
Total count 2
================================================
Family Heart Disease
No     4023
Yes    3977
Name: count, dtype: int64
Total count 2
================================================
Diabetes
No     4041
Yes    3959
Name: count, dtype: int64
Total count 2
================================================
High Blood Pressure
Yes    4052
No     3948
Name: count, dtype: int64
Total count 2
================================================
Low HDL Cholesterol
Yes    4043
No     3957
Name: count, dtype: int64
Total count 2
================================================
High LDL Cholesterol
No     4046
Yes    3954
Name: count, dtype: int64
Total count 2
================================================
Alcohol Consumption
Low       4083
Medium    1965
High      1952
Name: count, dtype: int64
Total count 3
================================================
Stress Level
Medium    2700
High      2655
Low       2645
Name: count, dtype: int64
Total count 3
================================================
Sugar Consumption
Low       2715
High      2668
Medium    2617
Name: count, dtype: int64
Total count 3
================================================
Heart Disease Status
No     6387
Yes    1613
Name: count, dtype: int64
Total count 2
================================================

In [10]:
from sklearn.preprocessing import LabelEncoder
X=data.drop(labels=["Heart Disease Status"],axis=1)
y=data["Heart Disease Status"]

In [11]:
cat_columns=X.select_dtypes(include="object").columns
num_columns=X.select_dtypes(exclude="object").columns

cat_columns
num_columns

Index(['Age', 'Blood Pressure', 'Cholesterol Level', 'BMI', 'Sleep Hours',
       'Triglyceride Level', 'Fasting Blood Sugar', 'CRP Level',
       'Homocysteine Level'],
      dtype='object')

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [13]:
num_pipeline = Pipeline(
    steps = [
        ("imputer",SimpleImputer(strategy="mean")),
        ("sclaer",StandardScaler())

    ]
)

In [14]:
Gender_categories=['Female','Male']
Exercise_Habits_categories=['High','Medium','Low']
Smoking_categories=['Yes','No']
Family_Heart_Disease_categories=['Yes','No']
Diabetes_categories=['Yes','No']
High_Blood_Pressure_categories=['Yes','No']
Low_HDL_Cholesterol_categories=['Yes','No']
High_LDL_Cholesterol_categories=['Yes','No']
Alcohol_Consumption_categories=['High','Medium','Low']
Stress_Level_categories=['High','Medium','Low']
Sugar_Consumption_categories=['High','Medium','Low']

In [15]:
from sklearn.preprocessing import OrdinalEncoder
cat_pipeline = Pipeline(
    steps = [
        ("imputer",SimpleImputer(strategy='most_frequent')),
        ("ordinal encoder",OrdinalEncoder(categories=[Gender_categories,Exercise_Habits_categories,Smoking_categories,Family_Heart_Disease_categories,Diabetes_categories,High_Blood_Pressure_categories,Low_HDL_Cholesterol_categories,High_LDL_Cholesterol_categories,Alcohol_Consumption_categories,Stress_Level_categories,Sugar_Consumption_categories]))



    ]
)

In [16]:
from sklearn.compose import ColumnTransformer
preprocessor =  ColumnTransformer(
    transformers=[
        ("num_pipeline", num_pipeline, num_columns),
        ("cat_pipeline", cat_pipeline, cat_columns)
    ]
)

In [17]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)




# Convert categorical labels ('Yes'/'No') to numerical (1/0)
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [19]:
print(X_train.shape) 
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(6400, 20)
(1600, 20)
(6400,)
(1600,)

In [20]:
preprocessor.fit_transform(X_train)
preprocessor.transform(X_test)

array([[ 1.21177184,  0.00980466,  0.47752028, ...,  2.        ,
         2.        ,  0.        ],
       [-1.71067582, -1.35494256,  0.9140806 , ...,  1.        ,
         0.        ,  0.        ],
       [-1.15927061, -0.61570448, -0.39560036, ...,  2.        ,
         1.        ,  1.        ],
       ...,
       [ 0.82578818, -0.72943342, -0.78620696, ...,  2.        ,
         0.        ,  2.        ],
       [-0.60786539,  1.60200975,  1.44254836, ...,  2.        ,
         0.        ,  0.        ],
       [ 0.16410192,  0.80590721,  1.14384919, ...,  2.        ,
         2.        ,  2.        ]])

In [21]:
preprocessor.get_feature_names_out()

array(['num_pipeline__Age', 'num_pipeline__Blood Pressure',
       'num_pipeline__Cholesterol Level', 'num_pipeline__BMI',
       'num_pipeline__Sleep Hours', 'num_pipeline__Triglyceride Level',
       'num_pipeline__Fasting Blood Sugar', 'num_pipeline__CRP Level',
       'num_pipeline__Homocysteine Level', 'cat_pipeline__Gender',
       'cat_pipeline__Exercise Habits', 'cat_pipeline__Smoking',
       'cat_pipeline__Family Heart Disease', 'cat_pipeline__Diabetes',
       'cat_pipeline__High Blood Pressure',
       'cat_pipeline__Low HDL Cholesterol',
       'cat_pipeline__High LDL Cholesterol',
       'cat_pipeline__Alcohol Consumption', 'cat_pipeline__Stress Level',
       'cat_pipeline__Sugar Consumption'], dtype=object)

In [22]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [23]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd

In [28]:
models = {
    'LogisticRegression': LogisticRegression(),
    'DecisionTree': DecisionTreeClassifier(),
    'RandomForest': RandomForestClassifier(),
    'SVM': SVC(),
    'KNN': KNeighborsClassifier(),
    'NaiveBayes': GaussianNB(),
    'GradientBoosting': GradientBoostingClassifier(),
    'XGBoost': XGBClassifier( eval_metric='logloss'),
    'RidgeClassifier': LogisticRegression(penalty='l2'),
    'LassoClassifier': LogisticRegression(penalty='l1', solver='liblinear')
}

In [29]:
def evaluate_model(true, pred):
    acc = accuracy_score(true, pred)
    prec = precision_score(true, pred,zero_division=1)
    rec = recall_score(true, pred,zero_division=1)
    f1 = f1_score(true, pred,zero_division=1)
    return acc, prec, rec, f1

# Lists to store results
model_list = []
accuracy_list = []
precision_list = []
recall_list = []
f1_list = []

# Train and evaluate each model
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    acc, prec, rec, f1 = evaluate_model(y_test, y_pred)
    
    print(f"Model: {name}")
    print(f"Accuracy: {acc:.4f}, Precision: {prec:.4f}, Recall: {rec:.4f}, F1-Score: {f1:.4f}")
    print("="*40, "\n")
    
    model_list.append(name)
    accuracy_list.append(acc)
    precision_list.append(prec)
    recall_list.append(rec)
    f1_list.append(f1)

Model: LogisticRegression
Accuracy: 0.7981, Precision: 1.0000, Recall: 0.0000, F1-Score: 0.0000
========================================

Model: DecisionTree
Accuracy: 0.6594, Precision: 0.1967, Recall: 0.2229, F1-Score: 0.2090
========================================

Model: RandomForest
Accuracy: 0.7981, Precision: 1.0000, Recall: 0.0000, F1-Score: 0.0000
========================================

Model: SVM
Accuracy: 0.7981, Precision: 1.0000, Recall: 0.0000, F1-Score: 0.0000
========================================

Model: KNN
Accuracy: 0.7625, Precision: 0.2336, Recall: 0.0774, F1-Score: 0.1163
========================================

Model: NaiveBayes
Accuracy: 0.7981, Precision: 1.0000, Recall: 0.0000, F1-Score: 0.0000
========================================

Model: GradientBoosting
Accuracy: 0.7963, Precision: 0.0000, Recall: 0.0000, F1-Score: 0.0000
========================================

Model: XGBoost
Accuracy: 0.7837, Precision: 0.2830, Recall: 0.0464, F1-Score: 0.0798
========================================

Model: RidgeClassifier
Accuracy: 0.7981, Precision: 1.0000, Recall: 0.0000, F1-Score: 0.0000
========================================

Model: LassoClassifier
Accuracy: 0.7981, Precision: 1.0000, Recall: 0.0000, F1-Score: 0.0000
========================================

In [26]:
results_df = pd.DataFrame({
    'Model': model_list,
    'Accuracy': accuracy_list,
    'Precision': precision_list,
    'Recall': recall_list,
    'F1-Score': f1_list
})

In [27]:
results_df = results_df.sort_values(by='F1-Score', ascending=False)
print(results_df)

                Model  Accuracy  Precision    Recall  F1-Score
1        DecisionTree  0.658750   0.214834  0.260062  0.235294
4                 KNN  0.762500   0.233645  0.077399  0.116279
7             XGBoost  0.783750   0.283019  0.046440  0.079787
0  LogisticRegression  0.798125   1.000000  0.000000  0.000000
2        RandomForest  0.798125   1.000000  0.000000  0.000000
3                 SVM  0.798125   1.000000  0.000000  0.000000
5          NaiveBayes  0.798125   1.000000  0.000000  0.000000
6    GradientBoosting  0.796250   0.000000  0.000000  0.000000
8     RidgeClassifier  0.798125   1.000000  0.000000  0.000000
9     LassoClassifier  0.798125   1.000000  0.000000  0.000000